# Generated by Django 5.2.3 on 2025-07-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
    ]
