# Generated by Django 5.2.3 on 2025-07-21 03:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_descriptor_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MOVING', 'Moving'), ('YARD_WORK', 'Yard Work'), ('CLEANING', 'Cleaning'), ('FOOD_SERVICE', 'Food Service'), ('SETUP_TEARDOWN', 'Setup/Teardown'), ('HOMELESS_CARE', 'Homeless Care'), ('CHILDCARE', 'Childcare'), ('ANIMAL_CARE', 'Animal Care'), ('FUNDRAISING', 'Fundraising'), ('COMMUNITY_OUTREACH', 'Community Outreach'), ('DONATION_SORTING', 'Donation Sorting'), ('OFFICE_HELP', 'Office Help'), ('ENVELOPE_STUFFING', 'Envelope Stuffing'), ('FESTIVAL_SUPPORT', 'Festival Support'), ('RACE_CREW', 'Race Crew'), ('PARKING_HELP', 'Parking Help'), ('BUILDING_CONSTRUCTION', 'Building Construction'), ('PAINTING', 'Painting'), ('OTHER', 'Other')], max_length=50), default=list, size=None),
        ),
    ]
