# Generated by Django 5.2.3 on 2025-07-21 03:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_event_descriptor_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_descriptor_tags',
            field=core.models.MultipleChoiceArrayField(base_field=models.CharField(choices=[('MOVING', 'Moving'), ('YARD_WORK', 'Yard Work'), ('CLEANING', 'Cleaning'), ('FOOD_SERVICE', 'Food Service'), ('SETUP_TEARDOWN', 'Setup/Teardown'), ('HOMELESS_CARE', 'Homeless Care'), ('CHILDCARE', 'Childcare'), ('ANIMAL_CARE', 'Animal Care'), ('FUNDRAISING', 'Fundraising'), ('COMMUNITY_OUTREACH', 'Community Outreach'), ('DONATION_SORTING', 'Donation Sorting'), ('OFFICE_HELP', 'Office Help'), ('ENVELOPE_STUFFING', 'Envelope Stuffing'), ('FESTIVAL_SUPPORT', 'Festival Support'), ('RACE_CREW', 'Race Crew'), ('PARKING_HELP', 'Parking Help'), ('BUILDING_CONSTRUCTION', 'Building Construction'), ('PAINTING', 'Painting'), ('OTHER', 'Other')], max_length=50), default=list, size=None),
        ),
    ]
